[project]
name = "pacman"
version = "0.1.0"
description = "Simple game - pacman"
readme = "README.md"
requires-python = "==3.13"
authors = ["Yuri Kozhanov <ykozhanov97@gmail.com>"]
dependencies = [
    "pygame==2.6.1",
]
